import { useState } from "react";
import { QRCodeSVG } from "qrcode.react";

export default function OTPQRCodeGenerator() {
  const [otpauthUrl, setOtpauthUrl] = useState("");

  const handleGenerate = () => {
    if (!otpauthUrl.startsWith("otpauth://")) {
      alert("Please enter a valid otpauth:// URL");
      return;
    }

    setOtpauthUrl(otpauthUrl.trim());
  };

  return (
    <div className="flex min-h-screen items-center justify-center bg-gray-100 p-6">
      <div className="w-full max-w-md rounded-xl bg-white p-6 shadow-lg">
        <h1 className="mb-2 text-2xl font-semibold">MFA QR Code Generator</h1>

        <p className="mb-6 text-sm text-gray-500">
          Enter the otpauth URI generated by your backend.
        </p>

        <div className="space-y-4">
          <textarea
            value={otpauthUrl}
            onChange={(e) => setOtpauthUrl(e.target.value)}
            placeholder="otpauth://totp/..."
            rows={4}
            className="w-full resize-none rounded-lg border border-gray-300 p-3 text-sm outline-none focus:border-black"
          />

          <button
            type="button"
            onClick={handleGenerate}
            className="w-full rounded-lg bg-black px-4 py-3 text-sm font-medium text-white transition hover:bg-gray-800"
          >
            Generate QR Code
          </button>
        </div>

        {otpauthUrl.startsWith("otpauth://") && (
          <div className="mt-8 flex flex-col items-center">
            <p className="mb-4 text-sm font-medium text-gray-700">
              Scan this QR code with your authenticator app
            </p>

            <div className="rounded-xl bg-white p-4 shadow">
              <QRCodeSVG
                value={otpauthUrl}
                size={256}
                level="M"
                includeMargin
              />
            </div>

            <p className="mt-4 break-all text-center text-xs text-gray-400">
              {otpauthUrl}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
